- name: Install ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible openssh-client

      # Sustituimos el agente por la creación manual y controlada del fichero
      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          # Las comillas dobles aquí son vitales para mantener los saltos de línea
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ejecutar Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          # Quitamos IdentitiesOnly, o si lo dejamos, Ansible ya sabrá qué fichero usar por defecto
          ANSIBLE_SSH_ARGS: "-o PreferredAuthentications=publickey"
        run: |
          # Le indicamos explícitamente a Ansible qué fichero de clave usar
          ansible-playbook -i ansible-web/host.ini ansible-web/tasks/main.yml --private-key ~/.ssh/id_rsa

