name: Docker Build & Publish

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible openssh-client

      - name: Clean default SSH keys
        run: |
          rm -f ~/.ssh/id_rsa ~/.ssh/id_rsa.pub || true

      - name: Start SSH agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Debug SSH agent
        run: |
          ssh-add -l

      - name: Ejecutar Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_SSH_ARGS: "-o IdentitiesOnly=yes -o PreferredAuthentications=publickey"
        run: |
          ansible-playbook -i ansible-web/host.ini ansible-web/instalar-docker.yml



