services:
  apache:
    build: ./apache
    container_name: apache
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/sites-enabled:/etc/apache2/sites-enabled:ro
      - ./apache/conf-enabled:/etc/apache2/conf-enabled:ro
      - ./apps/frontend:/var/www/frontend:ro
      - ./apps/phpapp:/var/www/phpapp:ro
      - ./apache/ca:/usr/local/share/ca-certificates/custom:ro
    depends_on:
      - php

  php:
    image: php:8.3-fpm-alpine
    container_name: php
    restart: unless-stopped
    volumes:
      - ./apps/phpapp:/var/www/phpapp:ro

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: unless-stopped
    network_mode: host

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
