name: Docker Build & Publish

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Deshabilitar host checking para evitar prompt interactivo
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Ejecutar Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_PYTHON_INTERPRETER: "auto_silent"
        run: |
          ansible-playbook -i ansible-web/host.ini ansible-web/tasks/main.yml --private-key ~/.ssh/id_rsa
